# Generated by Django 4.2.1 on 2023-05-31 06:17

import backend.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SideBarElement',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('content_id', enumchoicefield.fields.EnumChoiceField(enum_class=backend.models.Roles, max_length=10)),
            ],
        ),
    ]
