# Generated by Django 4.2.1 on 2023-06-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=50)),
            ],
            options={
                'db_table': 'page_blocks',
            },
        ),
        migrations.AlterModelOptions(
            name='sidebarelement',
            options={'permissions': (('permission_code', 'Friendly permition description'),)},
        ),
        migrations.AlterField(
            model_name='sidebarelement',
            name='id',
            field=models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='sidebarelement',
            table='sidebar_elements',
        ),
    ]
