# Generated by Django 4.2.1 on 2023-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pageblock_alter_sidebarelement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebarelement',
            old_name='content_id',
            new_name='content_acess',
        ),
        migrations.AddField(
            model_name='pageblock',
            name='content',
            field=models.CharField(db_column='content', default='fwefwfe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebarelement',
            name='code',
            field=models.CharField(db_column='code', default='efrfref', max_length=50),
            preserve_default=False,
        ),
    ]
